[package]
name = "amort"
version = "0.1.0"
authors = ["Kyle Prestel <kprestel@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"

[dev-dependencies]
float-cmp = "~0.5.2"
itertools = "0.8.1"
tempfile = "3.1.0"
assert_cmd = "0.11"
assert_fs = "0.11.3"
